const {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,ChannelType,Client,EmbedBuilder,Events,GatewayIntentBits,PermissionFlagsBits,REST,Routes,SlashCommandBuilder}=require('discord.js');
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));

function createBot(db){
 const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
 client.once(Events.ClientReady,async c=>{console.log(`[discord] ${c.user.tag} ready in ${c.guilds.cache.size} guild(s)`);if(String(process.env.AUTO_REGISTER_COMMANDS||'true')!=='false')await register().catch(console.error);});
 client.on(Events.InteractionCreate,i=>interaction({client,db,i}));
 client.on(Events.MessageCreate,m=>prefix({client,db,m}));
 client.on(Events.GuildMemberAdd,m=>memberJoin(db,m));
 return client;
}
function commands(){return[
 new SlashCommandBuilder().setName('ping').setDescription('Check bot latency'),
 new SlashCommandBuilder().setName('help').setDescription('Show MultiBot commands'),
 new SlashCommandBuilder().setName('ban').setDescription('Ban a member').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 new SlashCommandBuilder().setName('kick').setDescription('Kick a member').setDefaultMemberPermissions(PermissionFlagsBits.KickMembers).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 new SlashCommandBuilder().setName('purge').setDescription('Delete recent messages').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('amount').setDescription('1-100').setRequired(true).setMinValue(1).setMaxValue(100)),
 new SlashCommandBuilder().setName('ticket').setDescription('Ticket system').addSubcommand(s=>s.setName('open').setDescription('Open a ticket')).addSubcommand(s=>s.setName('close').setDescription('Close this ticket')).addSubcommand(s=>s.setName('panel').setDescription('Post ticket panel')),
 new SlashCommandBuilder().setName('verification-panel').setDescription('Post verification panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
 new SlashCommandBuilder().setName('twitch').setDescription('Twitch alert settings').addSubcommand(s=>s.setName('list').setDescription('List configured streamers')),
 new SlashCommandBuilder().setName('broadcast').setDescription('Owner broadcast to all bot servers').addStringOption(o=>o.setName('message').setDescription('Announcement').setRequired(true).setMaxLength(1900))
];}
async function register(){const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN),body=commands().map(c=>c.toJSON());if(process.env.DEV_GUILD_ID)await rest.put(Routes.applicationGuildCommands(process.env.DISCORD_CLIENT_ID,process.env.DEV_GUILD_ID),{body});else await rest.put(Routes.applicationCommands(process.env.DISCORD_CLIENT_ID),{body});console.log(`[discord] registered ${body.length} slash commands`);}
const eph=(content)=>({content,ephemeral:true});
async function interaction({client,db,i}){try{
 if(i.isButton())return button(client,db,i); if(!i.isChatInputCommand())return;
 if(i.commandName==='ping')return i.reply(eph(`Pong! ${client.ws.ping}ms`));
 if(i.commandName==='help')return i.reply({embeds:[help('/')],ephemeral:true});
 if(i.commandName==='ban'){const u=i.options.getUser('user',true),r=i.options.getString('reason')||`Banned by ${i.user.tag}`;const m=await i.guild.members.fetch(u.id).catch(()=>null);if(m&&!m.bannable)return i.reply(eph('I cannot ban that member.'));await i.guild.members.ban(u.id,{deleteMessageSeconds:86400,reason:r});return i.reply(eph(`Banned **${u.tag}**.`));}
 if(i.commandName==='kick'){const u=i.options.getUser('user',true),m=await i.guild.members.fetch(u.id).catch(()=>null);if(!m||!m.kickable)return i.reply(eph('I cannot kick that member.'));await m.kick(i.options.getString('reason')||`Kicked by ${i.user.tag}`);return i.reply(eph(`Kicked **${u.tag}**.`));}
 if(i.commandName==='purge'){const d=await i.channel.bulkDelete(i.options.getInteger('amount',true),true);return i.reply(eph(`Deleted ${d.size} message(s).`));}
 if(i.commandName==='ticket')return ticketSlash(client,db,i);
 if(i.commandName==='verification-panel')return verificationPanel(db,i);
 if(i.commandName==='twitch'){const s=await db.getGuildSettings(i.guild.id),rows=await db.listTwitchStreamers(i.guild.id);return i.reply(eph(`Twitch alerts: **${s.twitch_enabled?'enabled':'disabled'}**\n${rows.length?rows.map(x=>`https://twitch.tv/${x.twitch_login}`).join('\n'):'No users configured.'}`));}
 if(i.commandName==='broadcast'){if(i.user.id!==process.env.BOT_OWNER_ID)return i.reply(eph('Owner only.'));await i.deferReply({ephemeral:true});const r=await broadcast(client,db,i.user.id,i.options.getString('message',true));return i.editReply(`Broadcast complete: ${r.sent} sent, ${r.failed} failed.`);}
 }catch(e){console.error('[interaction]',e);const p=eph('Command failed. Check bot permissions/configuration.');if(i.replied||i.deferred)return i.followUp(p).catch(()=>{});return i.reply(p).catch(()=>{});}}
async function prefix({client,db,m}){if(!m.guild||m.author.bot)return;const s=await db.getGuildSettings(m.guild.id),p=s.prefix||'!';if(!m.content.startsWith(p))return;const a=m.content.slice(p.length).trim().split(/\s+/),c=(a.shift()||'').toLowerCase();try{
 if(c==='ping')return m.reply(`Pong! ${client.ws.ping}ms`);if(c==='help')return m.reply({embeds:[help(p)]});
 if(c==='ticket'){if((a[0]||'open')==='open')return m.reply(`Ticket created: ${await openTicket(client,db,m.guild,m.author)}`);if(a[0]==='close'){await closeTicket(db,m.channel,m.author,m.member);return;}if(a[0]==='panel'&&m.member.permissions.has(PermissionFlagsBits.ManageGuild))return sendTicketPanel(m.channel);}
 if(c==='verification-panel'&&m.member.permissions.has(PermissionFlagsBits.ManageGuild))return sendVerifyPanel(db,m.guild,m.channel);
 if(c==='broadcast'&&m.author.id===process.env.BOT_OWNER_ID){const st=await m.reply('Broadcasting...'),r=await broadcast(client,db,m.author.id,a.join(' '));return st.edit(`Broadcast complete: ${r.sent} sent, ${r.failed} failed.`);}
 }catch(e){console.error('[prefix]',e);m.reply('Command failed.').catch(()=>{});}}
function help(prefix){return new EmbedBuilder().setColor(0x5865f2).setTitle('MultiBot Commands').setDescription('Slash commands are preferred; prefix commands are retained as a backup.').addFields({name:'General',value:'`/ping`, `/help`, `/twitch list`'},{name:'Moderation',value:'`/ban`, `/kick`, `/purge`'},{name:'Tickets',value:'`/ticket open|close|panel`'},{name:'Verification',value:'`/verification-panel`'},{name:'Owner',value:'`/broadcast`'},{name:'Prefix',value:`${prefix}ping, ${prefix}ticket open`});}
async function ticketSlash(client,db,i){const sub=i.options.getSubcommand();if(sub==='open'){await i.deferReply({ephemeral:true});return i.editReply(`Ticket created: ${await openTicket(client,db,i.guild,i.user)}`);}if(sub==='close'){await i.deferReply({ephemeral:true});await closeTicket(db,i.channel,i.user,i.member);return i.editReply('Ticket closed; channel will be removed.');}if(!i.memberPermissions.has(PermissionFlagsBits.ManageGuild))return i.reply(eph('Manage Server required.'));await sendTicketPanel(i.channel);return i.reply(eph('Ticket panel posted.'));}
async function sendTicketPanel(channel){const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:create').setLabel('Create Ticket').setEmoji('🎫').setStyle(ButtonStyle.Primary));return channel.send({embeds:[new EmbedBuilder().setColor(0x5865f2).setTitle('Support Tickets').setDescription('Click below to create a private ticket.')],components:[row]});}
async function openTicket(client,db,guild,user){const existing=await db.findOpenTicketForUser(guild.id,user.id);if(existing){const c=guild.channels.cache.get(existing.channel_id);if(c)return c;}const s=await db.getGuildSettings(guild.id),cat=s.ticket_category_id&&guild.channels.cache.get(s.ticket_category_id),name=(user.username.toLowerCase().replace(/[^a-z0-9-]/g,'-')||'user').slice(0,40);const c=await guild.channels.create({name:`ticket-${name}`,type:ChannelType.GuildText,parent:cat?.type===ChannelType.GuildCategory?cat.id:undefined,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:client.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.ManageChannels]}]});await db.createTicket({guildId:guild.id,channelId:c.id,openerId:user.id});const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:close').setLabel('Close Ticket').setStyle(ButtonStyle.Danger));await c.send({content:`<@${user.id}>`,embeds:[new EmbedBuilder().setColor(0x57f287).setTitle('Ticket Opened').setDescription('Describe what you need help with.')],components:[row]});return c;}
async function closeTicket(db,channel,actor,member){const t=await db.findTicketByChannel(channel.id);if(!t)throw new Error('Not an open ticket');if(t.opener_id!==actor.id&&!member.permissions.has(PermissionFlagsBits.ManageChannels))throw new Error('Not allowed');const html=await transcript(channel);await db.closeTicket({channelId:channel.id,closedBy:actor.id,transcript:html});const s=await db.getGuildSettings(channel.guild.id),log=s.ticket_log_channel_id&&channel.guild.channels.cache.get(s.ticket_log_channel_id);if(log?.isTextBased())await log.send({content:`Ticket ${channel.name} closed by <@${actor.id}>.`,files:[new AttachmentBuilder(Buffer.from(html),{name:`ticket-${channel.id}.html`})]}).catch(()=>{});setTimeout(()=>channel.delete('Ticket closed').catch(()=>{}),2500);}
async function transcript(channel){const all=[];let before;for(let n=0;n<50;n++){const b=await channel.messages.fetch({limit:100,before});if(!b.size)break;all.push(...b.values());before=b.last().id;if(b.size<100)break;}all.sort((a,b)=>a.createdTimestamp-b.createdTimestamp);return `<!doctype html><meta charset="utf-8"><title>Ticket transcript</title><style>body{font-family:system-ui;background:#111827;color:#eee;padding:24px}article{border-bottom:1px solid #333;padding:10px}pre{white-space:pre-wrap}</style><h1>${esc(channel.name)}</h1>${all.map(m=>`<article><b>${esc(m.author?.tag||'Unknown')}</b> <small>${new Date(m.createdTimestamp).toISOString()}</small><pre>${esc(m.content||'')}</pre></article>`).join('')}`;}
async function verificationPanel(db,i){await sendVerifyPanel(db,i.guild,i.channel);return i.reply(eph('Verification panel posted.'));}
async function sendVerifyPanel(db,guild,channel){const s=await db.getGuildSettings(guild.id);if(!s.verification_enabled||!s.verified_role_id)throw new Error('Enable verification and choose a verified role in the dashboard first.');const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`verify:${guild.id}`).setLabel('Verify').setEmoji('✅').setStyle(ButtonStyle.Success));return channel.send({embeds:[new EmbedBuilder().setColor(0x57f287).setTitle('Member Verification').setDescription('Click Verify to receive server access.')],components:[row]});}
async function memberJoin(db,m){try{const s=await db.getGuildSettings(m.guild.id);if(!s.verification_enabled)return;if(s.unverified_role_id)await m.roles.add(s.unverified_role_id).catch(()=>{});if(!s.verified_role_id)return;const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`verify:${m.guild.id}`).setLabel('Verify').setStyle(ButtonStyle.Success));const payload={content:`Verify for **${m.guild.name}**`,components:[row]};if(!(await m.send(payload).then(()=>true).catch(()=>false))&&s.verification_channel_id){const c=m.guild.channels.cache.get(s.verification_channel_id);if(c?.isTextBased())await c.send({content:`<@${m.id}> verify below:`,components:[row]}).catch(()=>{});}}catch(e){console.error('[verification]',e);}}
async function button(client,db,i){if(i.customId==='ticket:create'){await i.deferReply({ephemeral:true});return i.editReply(`Ticket created: ${await openTicket(client,db,i.guild,i.user)}`);}if(i.customId==='ticket:close'){await i.deferReply({ephemeral:true});await closeTicket(db,i.channel,i.user,i.member);return i.editReply('Ticket closed.');}if(i.customId.startsWith('verify:')){const id=i.customId.split(':')[1],g=client.guilds.cache.get(id),s=await db.getGuildSettings(id),m=await g?.members.fetch(i.user.id).catch(()=>null);if(!g||!m||!s.verification_enabled||!s.verified_role_id)return i.reply(eph('Verification is unavailable.'));await m.roles.add(s.verified_role_id);if(s.unverified_role_id)await m.roles.remove(s.unverified_role_id).catch(()=>{});return i.reply(eph(`Verified in **${g.name}**.`));}}
async function broadcast(client,db,ownerId,message){if(!message?.trim())throw new Error('Message is required');let sent=0,failed=0;const embed=new EmbedBuilder().setColor(0x5865f2).setTitle('MultiBot Announcement').setDescription(message).setTimestamp();for(const g of client.guilds.cache.values()){try{const s=await db.getGuildSettings(g.id);let c=s.broadcast_channel_id&&g.channels.cache.get(s.broadcast_channel_id);if(!canSend(c,g))c=g.systemChannel;if(!canSend(c,g))c=g.channels.cache.find(x=>x.type===ChannelType.GuildText&&canSend(x,g));if(!c)throw new Error('No channel');await c.send({embeds:[embed]});sent++;}catch(e){failed++;}await sleep(500);}await db.logBroadcast({ownerId,message,sent,failed});return{sent,failed};}
function canSend(c,g){const me=g.members.me;return !!(c?.isTextBased?.()&&me&&c.permissionsFor(me)?.has([PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]));}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
module.exports={createBot,commands};
