const mysql = require('mysql2/promise');
const defaults={prefix:process.env.PREFIX||'!',verification_enabled:0,twitch_enabled:0};
async function createDatabase(){
 const pool=mysql.createPool({host:process.env.DATABASE_HOST,port:Number(process.env.DATABASE_PORT||3306),user:process.env.DATABASE_USER,password:process.env.DATABASE_PASSWORD||'',database:process.env.DATABASE_NAME,waitForConnections:true,connectionLimit:Number(process.env.DATABASE_CONNECTION_LIMIT||10),charset:'utf8mb4'});
 await pool.query('SELECT 1');await migrate(pool);
 return {pool,end:()=>pool.end(),
 async getGuildSettings(guildId){const[rows]=await pool.execute('SELECT * FROM guild_settings WHERE guild_id = ?',[guildId]);return{...defaults,...(rows[0]||{}),guild_id:guildId};},
 async saveGuildSettings(guildId,input){const f=['prefix','verification_enabled','verified_role_id','unverified_role_id','verification_channel_id','ticket_category_id','ticket_log_channel_id','broadcast_channel_id','twitch_enabled','twitch_channel_id','twitch_role_id'],d=Object.fromEntries(f.map(k=>[k,input[k]??null]));d.prefix=String(d.prefix||process.env.PREFIX||'!').slice(0,10);d.verification_enabled=d.verification_enabled?1:0;d.twitch_enabled=d.twitch_enabled?1:0;await pool.execute(`INSERT INTO guild_settings (guild_id,prefix,verification_enabled,verified_role_id,unverified_role_id,verification_channel_id,ticket_category_id,ticket_log_channel_id,broadcast_channel_id,twitch_enabled,twitch_channel_id,twitch_role_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE prefix=VALUES(prefix),verification_enabled=VALUES(verification_enabled),verified_role_id=VALUES(verified_role_id),unverified_role_id=VALUES(unverified_role_id),verification_channel_id=VALUES(verification_channel_id),ticket_category_id=VALUES(ticket_category_id),ticket_log_channel_id=VALUES(ticket_log_channel_id),broadcast_channel_id=VALUES(broadcast_channel_id),twitch_enabled=VALUES(twitch_enabled),twitch_channel_id=VALUES(twitch_channel_id),twitch_role_id=VALUES(twitch_role_id)`,[guildId,d.prefix,d.verification_enabled,d.verified_role_id,d.unverified_role_id,d.verification_channel_id,d.ticket_category_id,d.ticket_log_channel_id,d.broadcast_channel_id,d.twitch_enabled,d.twitch_channel_id,d.twitch_role_id]);return this.getGuildSettings(guildId);},
 async listTwitchStreamers(guildId){const[r]=await pool.execute('SELECT twitch_login,last_stream_id FROM twitch_streamers WHERE guild_id=? ORDER BY twitch_login',[guildId]);return r;},
 async replaceTwitchStreamers(guildId,logins){const cleaned=[...new Set(logins.map(v=>String(v).trim().toLowerCase()).filter(Boolean))].slice(0,100),c=await pool.getConnection();try{await c.beginTransaction();for(const login of cleaned)await c.execute('INSERT IGNORE INTO twitch_streamers (guild_id,twitch_login) VALUES (?,?)',[guildId,login]);if(cleaned.length){const p=cleaned.map(()=>'?').join(',');await c.execute(`DELETE FROM twitch_streamers WHERE guild_id=? AND twitch_login NOT IN (${p})`,[guildId,...cleaned]);}else await c.execute('DELETE FROM twitch_streamers WHERE guild_id=?',[guildId]);await c.commit();}catch(e){await c.rollback();throw e}finally{c.release()}return this.listTwitchStreamers(guildId);},
 async listEnabledTwitchTargets(){const[r]=await pool.query('SELECT ts.guild_id,ts.twitch_login,ts.last_stream_id,gs.twitch_channel_id,gs.twitch_role_id FROM twitch_streamers ts JOIN guild_settings gs ON gs.guild_id=ts.guild_id WHERE gs.twitch_enabled=1 AND gs.twitch_channel_id IS NOT NULL');return r;},
 async setTwitchLastStream(guildId,login,streamId){await pool.execute('UPDATE twitch_streamers SET last_stream_id=? WHERE guild_id=? AND twitch_login=?',[streamId||null,guildId,login]);},
 async findOpenTicketForUser(guildId,openerId){const[r]=await pool.execute("SELECT * FROM tickets WHERE guild_id=? AND opener_id=? AND status='open' ORDER BY id DESC LIMIT 1",[guildId,openerId]);return r[0]||null;},
 async findTicketByChannel(channelId){const[r]=await pool.execute("SELECT * FROM tickets WHERE channel_id=? AND status='open' LIMIT 1",[channelId]);return r[0]||null;},
 async createTicket({guildId,channelId,openerId}){const[r]=await pool.execute("INSERT INTO tickets (guild_id,channel_id,opener_id,status) VALUES (?,?,?,'open')",[guildId,channelId,openerId]);return r.insertId;},
 async closeTicket({channelId,closedBy,transcript}){await pool.execute("UPDATE tickets SET status='closed',closed_by=?,transcript_html=?,closed_at=CURRENT_TIMESTAMP WHERE channel_id=? AND status='open'",[closedBy,transcript,channelId]);},
 async logBroadcast({ownerId,message,sent,failed}){await pool.execute('INSERT INTO broadcast_logs (owner_id,message,sent_count,failed_count) VALUES (?,?,?,?)',[ownerId,message,sent,failed]);}
 };}
async function migrate(pool){
 await pool.query(`CREATE TABLE IF NOT EXISTS guild_settings (guild_id VARCHAR(32) PRIMARY KEY,prefix VARCHAR(10) NOT NULL DEFAULT '!',verification_enabled TINYINT(1) NOT NULL DEFAULT 0,verified_role_id VARCHAR(32) NULL,unverified_role_id VARCHAR(32) NULL,verification_channel_id VARCHAR(32) NULL,ticket_category_id VARCHAR(32) NULL,ticket_log_channel_id VARCHAR(32) NULL,broadcast_channel_id VARCHAR(32) NULL,twitch_enabled TINYINT(1) NOT NULL DEFAULT 0,twitch_channel_id VARCHAR(32) NULL,twitch_role_id VARCHAR(32) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
 await pool.query(`CREATE TABLE IF NOT EXISTS twitch_streamers (guild_id VARCHAR(32) NOT NULL,twitch_login VARCHAR(64) NOT NULL,last_stream_id VARCHAR(64) NULL,PRIMARY KEY(guild_id,twitch_login),CONSTRAINT fk_twitch_guild FOREIGN KEY(guild_id) REFERENCES guild_settings(guild_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
 await pool.query(`CREATE TABLE IF NOT EXISTS tickets (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,guild_id VARCHAR(32) NOT NULL,channel_id VARCHAR(32) NOT NULL UNIQUE,opener_id VARCHAR(32) NOT NULL,closed_by VARCHAR(32) NULL,status ENUM('open','closed') NOT NULL DEFAULT 'open',transcript_html LONGTEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at TIMESTAMP NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
 await pool.query(`CREATE TABLE IF NOT EXISTS broadcast_logs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,owner_id VARCHAR(32) NOT NULL,message TEXT NOT NULL,sent_count INT NOT NULL DEFAULT 0,failed_count INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
}
module.exports={createDatabase};
