const crypto=require('crypto'),express=require('express'),session=require('express-session');
const ADMIN=1n<<3n;
function createDashboard({client,db}){const app=express();app.set('trust proxy',1);app.use(express.urlencoded({extended:false,limit:'100kb'}));app.use(session({secret:process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex'),resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:String(process.env.COOKIE_SECURE||'').toLowerCase()==='true',maxAge:43200000}}));
 app.get('/',(q,s)=>s.send(page('MultiBot',`<main><h1>MultiBot Dashboard</h1><p>Configure tickets, verification, Twitch alerts, command prefix and broadcast channels.</p><a class="btn" href="${q.session.user?'/dashboard':'/login'}">${q.session.user?'Open Dashboard':'Login with Discord'}</a></main>`)));
 app.get('/login',(q,s)=>{if(!process.env.DISCORD_CLIENT_SECRET||!process.env.DISCORD_REDIRECT_URI)return s.status(500).send('Discord OAuth is not configured.');const state=crypto.randomBytes(24).toString('hex');q.session.state=state;const u=new URL('https://discord.com/oauth2/authorize');u.searchParams.set('client_id',process.env.DISCORD_CLIENT_ID);u.searchParams.set('redirect_uri',process.env.DISCORD_REDIRECT_URI);u.searchParams.set('response_type','code');u.searchParams.set('scope','identify guilds');u.searchParams.set('state',state);s.redirect(u.toString());});
 app.get('/callback',async(q,s,n)=>{try{if(!q.query.code||q.query.state!==q.session.state)return s.status(400).send('Invalid OAuth state');const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:String(q.query.code),redirect_uri:process.env.DISCORD_REDIRECT_URI}),r=await fetch('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`OAuth failed: ${r.status}`);const t=await r.json();q.session.access=t.access_token;q.session.user=await api('/users/@me',t.access_token);q.session.guilds=await api('/users/@me/guilds',t.access_token);q.session.csrf=crypto.randomBytes(24).toString('hex');s.redirect('/dashboard');}catch(e){n(e);}});
 app.get('/logout',(q,s)=>q.session.destroy(()=>s.redirect('/')));
 app.get('/dashboard',login,async(q,s,n)=>{try{await refresh(q);const gs=q.session.guilds.filter(g=>manage(g)&&client.guilds.cache.has(g.id));s.send(page('Servers',`<nav><a href="/">MultiBot</a><a href="/logout">Logout</a></nav><main><h1>Your Servers</h1><div class="grid">${gs.map(g=>`<a class="card" href="/guild/${g.id}"><h3>${e(g.name)}</h3><p>Configure MultiBot</p></a>`).join('')||'<p>No manageable shared servers.</p>'}</div></main>`));}catch(x){n(x);}});
 app.get('/guild/:id',login,guard(client),async(q,s,n)=>{try{const g=client.guilds.cache.get(q.params.id),x=await db.getGuildSettings(g.id),tw=await db.listTwitchStreamers(g.id),roles=[...g.roles.cache.values()].filter(r=>r.id!==g.id).sort((a,b)=>b.position-a.position),texts=[...g.channels.cache.values()].filter(c=>c.isTextBased?.()&&c.type!==4),cats=[...g.channels.cache.values()].filter(c=>c.type===4),opts=(arr,sel,pre='')=>'<option value="">None</option>'+arr.map(v=>`<option value="${v.id}" ${String(v.id)===String(sel||'')?'selected':''}>${e(pre+(v.name||''))}</option>`).join('');
 s.send(page(g.name,`<nav><a href="/dashboard">← Servers</a><b>${e(g.name)}</b></nav><main><h1>${e(g.name)}</h1><form method="post"><input type="hidden" name="csrf" value="${q.session.csrf}">
 ${section('Commands',`<label>Prefix<input name="prefix" maxlength="10" value="${e(x.prefix||'!')}"></label>`)}
 ${section('Member Verification',`<label class="check"><input type="checkbox" name="verification_enabled" ${x.verification_enabled?'checked':''}> Enable verification</label><label>Verified role<select name="verified_role_id">${opts(roles,x.verified_role_id)}</select></label><label>Unverified role<select name="unverified_role_id">${opts(roles,x.unverified_role_id)}</select></label><label>Fallback verification channel<select name="verification_channel_id">${opts(texts,x.verification_channel_id,'#')}</select></label>`)}
 ${section('Tickets',`<label>Ticket category<select name="ticket_category_id">${opts(cats,x.ticket_category_id)}</select></label><label>Transcript log channel<select name="ticket_log_channel_id">${opts(texts,x.ticket_log_channel_id,'#')}</select></label>`)}
 ${section('Broadcasts',`<label>Preferred channel<select name="broadcast_channel_id">${opts(texts,x.broadcast_channel_id,'#')}</select></label>`)}
 ${section('Twitch',`<label class="check"><input type="checkbox" name="twitch_enabled" ${x.twitch_enabled?'checked':''}> Enable Twitch alerts</label><label>Announcement channel<select name="twitch_channel_id">${opts(texts,x.twitch_channel_id,'#')}</select></label><label>Mention role<select name="twitch_role_id">${opts(roles,x.twitch_role_id)}</select></label><label>Twitch usernames<textarea name="twitch_users" rows="5">${e(tw.map(z=>z.twitch_login).join(', '))}</textarea></label>`)}
 <button>Save Settings</button></form></main>`));}catch(x){n(x);}});
 app.post('/guild/:id',login,guard(client),async(q,s,n)=>{try{if(q.body.csrf!==q.session.csrf)return s.status(403).send('Invalid CSRF');const id=q.params.id,clean=v=>/^\d{15,22}$/.test(String(v||''))?String(v):null;await db.saveGuildSettings(id,{prefix:String(q.body.prefix||'!').slice(0,10),verification_enabled:q.body.verification_enabled==='on',verified_role_id:clean(q.body.verified_role_id),unverified_role_id:clean(q.body.unverified_role_id),verification_channel_id:clean(q.body.verification_channel_id),ticket_category_id:clean(q.body.ticket_category_id),ticket_log_channel_id:clean(q.body.ticket_log_channel_id),broadcast_channel_id:clean(q.body.broadcast_channel_id),twitch_enabled:q.body.twitch_enabled==='on',twitch_channel_id:clean(q.body.twitch_channel_id),twitch_role_id:clean(q.body.twitch_role_id)});await db.replaceTwitchStreamers(id,String(q.body.twitch_users||'').split(/[\s,]+/).map(v=>v.replace(/^https?:\/\/(www\.)?twitch\.tv\//i,'').replace(/^@/,'')).filter(Boolean));s.redirect(`/guild/${id}`);}catch(x){n(x);}});
 app.use((x,q,s,n)=>{console.error('[web]',x);if(s.headersSent)return n(x);s.status(500).send(page('Error',`<main><h1>Error</h1><p>${e(x.message)}</p></main>`));});return app;}
function login(q,s,n){if(!q.session?.user||!q.session?.access)return s.redirect('/login');n();}
function guard(client){return async(q,s,n)=>{try{await refresh(q);const g=q.session.guilds.find(x=>x.id===q.params.id);if(!g||!manage(g)||!client.guilds.cache.has(g.id))return s.status(403).send('Not authorized');n();}catch(x){n(x);}}}
async function refresh(q){q.session.guilds=await api('/users/@me/guilds',q.session.access);}
function manage(g){if(g.owner)return true;try{return(BigInt(g.permissions||'0')&ADMIN)===ADMIN}catch{return false}}
async function api(path,t){const r=await fetch('https://discord.com/api/v10'+path,{headers:{Authorization:'Bearer '+t}});if(!r.ok)throw new Error(`Discord API failed: ${r.status}`);return r.json();}
function section(h,b){return`<section><h2>${h}</h2>${b}</section>`;}function e(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function page(t,b){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(t)} · MultiBot</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:#0b1020;color:#eef2ff}a{color:#aeb7ff;text-decoration:none}nav,main{max-width:1050px;margin:auto;padding:22px}nav{display:flex;justify-content:space-between;border-bottom:1px solid #293452}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px}.card,section{display:block;background:#151c32;border:1px solid #293452;border-radius:14px;padding:18px;margin-bottom:16px}label{display:block;margin:12px 0}input,select,textarea{width:100%;padding:10px;margin-top:6px;background:#0d1427;color:white;border:1px solid #35415f;border-radius:8px}.check{display:flex;gap:8px}.check input{width:auto}.btn,button{display:inline-block;background:#5865f2;color:white;border:0;border-radius:9px;padding:11px 16px;font-weight:700}</style></head><body>${b}</body></html>`;}
module.exports={createDashboard};